# Generated by Django 3.0.6 on 2021-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='trump.jpg', upload_to='profile_pics'),
        ),
    ]
