# Generated by Django 3.0.6 on 2021-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211017_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='trump.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
